
% Read in Excel worksheet generated by addCellNums and add rate maps, count
% maps, and, optionally, spikes and positions. Saves result in mat file.
%
%   USAGE
%       [counts,centers,thetaToDelta] = thetaIndex(spikes)
%       spikes          vector of spike timestamps
%       
%   OUTPUT
%       counts          bin counts from histogram of autocorrelation
%       centers         bin centers from histogram of autocorrelation
%       thetaToDelta    ratio of theta-band power to delta-band power
%
%   NOTES
%       Will not work well for small number of spikes (i.e. < 100).
%
% Written by BRK 2016

function thetaInd = thetaIndexLFP(folder,tetrode)

%% get data
filename = [folder '\' sprintf('CSC%s.ncs',num2str(tetrode))];
[Timestamp, ChanNum, SampleFrequency, NumValSamples, Samples, Header] = Nlx2MatCSC(filename,[1 1 1 1 1],1,1);
squeezedSamples = reshape(Samples,512*size(Samples,2),1);
squeezedSamples = squeezedSamples * 0.0024;

%% resample and detrend
srate0 = SampleFrequency(1);
rsrate = 500;
resampled = resample(squeezedSamples,rsrate,srate0);
ds = detrend(resampled);

%% FFT
nData = 2000000;
nHz = floor(nData/2)+1;
sineX = fft(ds,nData)/nData;
hz = linspace(0.1,rsrate/2,nHz);
tb = dsearchn(hz',[5 11]');
bb = dsearchn(hz',[0 50]');
db = dsearchn(hz',[1 4]');
Power = 2*abs(sineX(1:length(hz)));
% plot(hz,Power)
% xlim([0 20])

%% theta index
peakTheta = nanmax(Power(tb(1):tb(2)));
[~,peakThetaInd] = nanmin(abs(Power-peakTheta));
length1Hz = round(nHz/(rsrate/2));
thetaPower = nanmean(Power(peakThetaInd-length1Hz:peakThetaInd+length1Hz));
bbPower = nanmean(Power(bb(1):bb(2)));
dbPower = nanmean(Power(db(1):db(2)));
thetaInd = thetaPower/bbPower;
thetaDelta = thetaPower/dbPower;

